kind: pipeline
name: main

workspace:
  base: /go
  path: src/github.com/pfillion/helloworld

steps:
- name: go-build
  image: golang
  commands:
  - make go-build

- name: go-test
  image: golang
  commands:
  - make go-test

- name: docker-build
  image: pfillion/drone-dind
  volumes:
  - name: docker_volume
    path: /var/run
  commands:
  - make docker-build

- name: docker-test
  image: pfillion/drone-dind
  volumes:
  - name: docker_volume
    path: /var/run
  commands:
  - make docker-run

- name: docker-push
  image: pfillion/drone-dind
  volumes:
  - name: docker_volume
    path: /var/run
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - make docker-push

- name: notify-microbadger
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhook_urls

services:
- name: docker
  image: pfillion/drone-dind
  privileged: true
  volumes:
  - name: docker_volume
    path: /var/run

volumes:
- name: docker_volume
  temp: {}