when:
  - event: [push, manual]

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
      - echo "ls" > executable.sh
      - chmod 0755 executable.sh
  - name: a-test-step
    image: alpine
    commands:
      - echo "Testing ..."
      - ./executable.sh