when:
  - event: [push, manual]

workspace:
  base: /go
  path: src/github.com/pfillion/helloworld

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  - name: go-build
    image: pfillion/drone-golang
    commands:
      - make go-install go-build

  - name: go-test
    image: pfillion/drone-golang
    commands:
      - make go-test

  - name: docker-build
    image: pfillion/drone-dind
    commands:
      - make docker-build
    volumes: 
      - /var/run:/var/run

  - name: docker-test
    image: pfillion/drone-dind
    commands:
      - make docker-test
    volumes: 
      - /var/run:/var/run

  - name: docker-push
    image: pfillion/drone-dind
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - make docker-push
    volumes: 
      - /var/run:/var/run      
    when:
      - evaluate: 'MODE_LOCAL != "true"'

  - name: notify-goreportcard
    image: appropriate/curl
    commands:
      - curl -sS -d "repo=github.com/pfillion/helloworld" https://goreportcard.com/checks
    when:
      - evaluate: 'MODE_LOCAL != "true"'